export const QUERY_KEY_USER_INFO = 'UserInfo'
export const QUERY_KEY_MY_MEDIAS = 'MyMedias'
export const QUERY_KEY_MEDIA_SEARCH = 'MediaInfo_Search'
export const QUERY_KEY_MORELIKE_MEDIAS = 'MoreLike_Medias'
export const QUERY_KEY_AI_SEARCH = 'AI_Search'
