interface MediaInfoTmp {
  id?: string
  mediaId?: string | null
  titleImg?: string | null
  mainCategory?: string | null
  subCategory?: string | null
  mediaType?: string | null
  madeAt?: string | null
  title?: string | null
  casts?: string[] | null
  genres?: string[] | null
  impressions?: string[] | null
  ratingSymbol?: string | null
  ratingDetails?: string[] | null
  description?: string | null
  previewMainImg?: string | null
  previewTitleImg?: string | null
  previewTrailer?: string | null
}

export const MEDIA_DATA: MediaInfoTmp[] = [
  {
    mediaId: 'mediaId 1',
    titleImg: 'titleImg 1',
    mainCategory: '6',
    subCategory: '8',
    mediaType: 'mediaType 1',
    madeAt: '1999-12-08T16:49:54.107Z',
    title: 'Matrix',
    casts: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    genres: ['Sci-Fi Movies', 'Classic Movies', 'Martial Arts Movies'],
    impressions: ['Mind-Bending', 'Dystopian', 'Cyberpunk'],
    ratingSymbol: 'R',
    ratingDetails: ['sci-fi violence', 'brief language'],
    description:
      'Inventore illum sunt laborum minima. Iure doloremque praesentium doloribus cum. Excepturi corrupti provident. Occaecati quia doloribus. Unde libero nam facere.',
    id: '1',
  },
  {
    mediaId: 'mediaId 2',
    titleImg: 'titleImg 2',
    mainCategory: '7',
    subCategory: '5',
    mediaType: 'mediaType 2',
    madeAt: '2025-01-13T20:59:52.080Z',
    title: 'Breaking Bad',
    casts: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
    genres: ['TV Dramas', 'Crime TV Show', 'TV Thrillers'],
    impressions: ['Violent', 'Gritty', 'Dark'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'smoking', 'substances', 'violence'],
    description:
      'Eius aspernatur et consectetur adipisci nam unde. Magnam sequi voluptates distinctio dolor commodi odio. Qui totam doloribus qui necessitatibus praesentium. Reprehenderit dolor hic doloremque. Temporibus nihil fuga voluptas ipsum vel.',
    id: '2',
  },
  {
    mediaId: 'mediaId 3',
    titleImg: 'titleImg 3',
    mainCategory: '2',
    subCategory: '9',
    mediaType: 'mediaType 3',
    madeAt: '2024-03-12T14:00:46.856Z',
    title: 'Squid Game',
    casts: ['Lee Jung-jae', 'Lee Byung-hun', 'Yim Si-wan'],
    genres: ['TV Dramas', 'Korean', 'TV Thrillers'],
    impressions: ['Violent', 'Suspenseful', 'Thriller'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'smoking', 'violence'],
    description:
      'Itaque laudantium accusamus libero quae. Voluptas odit consequuntur quia architecto consectetur ut.',
    id: '3',
  },
  {
    mediaId: 'mediaId 4',
    titleImg: 'titleImg 4',
    mainCategory: '6',
    subCategory: '3',
    mediaType: 'mediaType 4',
    madeAt: '2024-11-19T06:16:42.110Z',
    title: 'X-Men: Days of Future Past',
    casts: ['Hugh Jackman', 'James McAvoy', 'Michael Fassbender'],
    genres: ['Super Heroes', 'Science Fiction'],
    impressions: ['Thriller', 'Adventure'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['sci-fi violence', 'language'],
    description:
      'Numquam nulla dolores perspiciatis. Voluptas quam harum distinctio quae possimus consectetur quam voluptas est.',
    id: '4',
  },
  {
    mediaId: 'mediaId 5',
    titleImg: 'titleImg 5',
    mainCategory: '2',
    subCategory: '2',
    mediaType: 'mediaType 5',
    madeAt: '2024-10-23T05:51:45.021Z',
    title: 'Terminator 2: Judgment Day',
    casts: ['Arnold Schwarzenegger', 'Linda Hamilton', 'Edward Furlong'],
    genres: ['Sci-Fi Movies', 'Classic Movies'],
    impressions: ['Violent'],
    ratingSymbol: 'R',
    ratingDetails: ['strong sci-fi action', 'violence'],
    description:
      'Cupiditate animi molestiae amet a ducimus libero. Sit dolores perspiciatis totam possimus nostrum ipsum nihil quis alias.',
    id: '5',
  },
  {
    mediaId: 'mediaId 6',
    titleImg: 'titleImg 6',
    mainCategory: '2',
    subCategory: '8',
    mediaType: 'mediaType 6',
    madeAt: '2025-02-15T11:15:28.936Z',
    title: 'The Lord of the Rings: The Return of the King',
    casts: ['Elijah Wood', 'Karl Urban', 'Andy Serkis'],
    genres: ['Adventure', 'Fantasy', 'Action'],
    impressions: ['Violent', 'Ambitious', 'Compelling'],
    ratingSymbol: '14A',
    ratingDetails: ['violence', 'alcohol use', 'language'],
    description:
      'Doloribus necessitatibus dolores error. Praesentium itaque nobis aspernatur. Eligendi provident tempora aliquam.',
    id: '6',
  },
  {
    mediaId: 'mediaId 7',
    titleImg: 'titleImg 7',
    mainCategory: '5',
    subCategory: '2',
    mediaType: 'mediaType 7',
    madeAt: '2025-02-21T21:35:31.813Z',
    title: 'Better Call Saul',
    casts: ['Bob Odenkirk', 'Jonathan Banks', 'Rhea Seehorn'],
    genres: ['TV Dramas', 'Crime TV Shows'],
    impressions: ['Offbeat', 'Gritty'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'smoking', 'suicide'],
    description:
      'Sapiente sed facilis omnis. Blanditiis fuga nostrum animi dolorem.',
    id: '7',
  },
  {
    mediaId: 'mediaId 8',
    titleImg: 'titleImg 8',
    mainCategory: '2',
    subCategory: '2',
    mediaType: 'mediaType 8',
    madeAt: '2024-11-07T11:56:48.463Z',
    title: 'Interstellar',
    casts: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    genres: ['Sci-Fi Movies', 'Drama Movies'],
    impressions: ['Mind-Bending', 'Cerebral'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['some intense perilous action'],
    description:
      'Voluptates sapiente nesciunt officia ad iusto facere harum qui eaque. Modi tenetur amet expedita.',
    id: '8',
  },
  {
    mediaId: 'mediaId 9',
    titleImg: 'titleImg 9',
    mainCategory: '2',
    subCategory: '9',
    mediaType: 'mediaType 9',
    madeAt: '2024-09-29T15:34:08.352Z',
    title: 'The Defenders',
    casts: ['Finn Jones', 'Mike Colter', 'Charlie Cox'],
    genres: ['Action', 'Drama', 'Superhero'],
    impressions: ['Violent'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['violence', 'language'],
    description:
      'Odio corrupti doloribus. Corporis alias porro maiores ducimus molestiae dicta.',
    id: '9',
  },
  {
    mediaId: 'mediaId 10',
    titleImg: 'titleImg 10',
    mainCategory: '2',
    subCategory: '3',
    mediaType: 'mediaType 10',
    madeAt: '2024-12-27T11:30:46.028Z',
    title: 'X-Men: Apocalypse',
    casts: ['James McAvoy', 'Michael Fassbender', 'Jennifer Lawrence'],
    genres: ['Superhero', 'Action', 'Sci-Fi Movies'],
    impressions: ['Thriller', 'Adventure'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['sci-fi violence', 'language'],
    description:
      'Illo tempora ea nemo. Possimus nam dignissimos nemo explicabo maxime aspernatur nemo placeat. Fuga alias rem. Unde totam corrupti sapiente repudiandae earum beatae autem fugit.',
    id: '10',
  },
  {
    mediaId: 'mediaId 11',
    titleImg: 'titleImg 11',
    mainCategory: '5',
    subCategory: '3',
    mediaType: 'mediaType 11',
    madeAt: '2024-10-15T15:45:46.937Z',
    title: 'Pulp Fiction',
    casts: [
      'John Travolta',
      'Samuel L. Jackson',
      'Uma Thurman',
      'Harvey Keitel',
      'Bruce Willis',
    ],
    genres: ['Classic Movies', 'Drama'],
    impressions: ['Offbeat', 'Chilling', 'Ominous'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'drug use', 'smoking', 'language'],
    description:
      'Non incidunt odio labore deleniti dolor repellat ratione. Id ratione autem perspiciatis cupiditate quo iste laboriosam. Culpa blanditiis quae temporibus nisi tempora. Debitis quisquam eveniet a ex hic et temporibus non sapiente. Rerum beatae similique earum quaerat. Voluptate suscipit molestiae incidunt tempora commodi.',
    id: '11',
  },
  {
    mediaId: 'mediaId 12',
    titleImg: 'titleImg 12',
    mainCategory: '2',
    subCategory: '6',
    mediaType: 'mediaType 12',
    madeAt: '2024-11-15T09:59:57.311Z',
    title: 'Ghost in the Shell',
    casts: ['Scarlett Johansson', 'Michael Carmen'],
    genres: ['Action', 'Sci-Fi'],
    impressions: ['Dystopian', 'Cyberpunk'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['violence', 'suggestive content'],
    description:
      'Eos magnam repudiandae. Animi sapiente iure maxime. Molestias enim iste quod totam.',
    id: '12',
  },
  {
    mediaId: 'mediaId 13',
    titleImg: 'titleImg 13',
    mainCategory: '2',
    subCategory: '1',
    mediaType: 'mediaType 13',
    madeAt: '2024-05-27T13:38:38.901Z',
    title: 'Good Will Hunting',
    casts: ['Matt Damon', 'Robin Williams', 'Ben Affleck'],
    genres: ['Drama movies', 'Classic movies'],
    impressions: ['Sentimental', 'Bittersweet', 'Heartfelt'],
    ratingSymbol: 'R',
    ratingDetails: ['strong language'],
    description:
      'Mollitia numquam et iure quibusdam amet accusamus. Officia sit et explicabo est tempora voluptatum vitae. Praesentium vel voluptatem dolorem.',
    id: '13',
  },
  {
    mediaId: 'mediaId 14',
    titleImg: 'titleImg 14',
    mainCategory: '4',
    subCategory: '3',
    mediaType: 'mediaType 14',
    madeAt: '2024-11-21T13:39:18.237Z',
    title: 'Sweet Home',
    casts: ['Song Kang', 'Lee Jin-uk', 'Lee Si-young'],
    genres: ['TV Dramas', 'Korean'],
    impressions: ['Scary', 'Dark', 'Suspenseful'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'nudity'],
    description:
      'Possimus impedit consequuntur vel ab vitae iusto unde assumenda corporis. Ut earum pariatur harum totam placeat ipsa ducimus animi. Labore illo possimus deleniti eveniet amet accusamus quia sapiente quo.',
    id: '14',
  },
  {
    mediaId: 'mediaId 15',
    titleImg: 'titleImg 15',
    mainCategory: '6',
    subCategory: '5',
    mediaType: 'mediaType 15',
    madeAt: '2025-03-10T00:28:54.227Z',
    title: 'John Wick',
    casts: ['Keanu Reeves', 'Michael Nyqvist', 'Alfie Allen'],
    genres: ['Action', 'Adventure Movies'],
    impressions: ['Violent', 'Gritty'],
    ratingSymbol: 'R',
    ratingDetails: ['strong and bloody violence'],
    description:
      'Eum eius itaque expedita neque ea delectus. Suscipit repellat hic odit sapiente vel sed iure quia. Doloribus cum perferendis eos rem asperiores recusandae.',
    id: '15',
  },
  {
    mediaId: 'mediaId 16',
    titleImg: 'titleImg 16',
    mainCategory: '8',
    subCategory: '7',
    mediaType: 'mediaType 16',
    madeAt: '2024-07-25T03:59:43.980Z',
    title: 'White House Down',
    casts: ['Channing Tatum', 'Jamie Foxx', 'Maggie Gyllenhaal'],
    genres: ['Action', 'Adventure Movies'],
    impressions: ['Explosive', 'Adrenaline Rush'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['action', 'violence', 'language'],
    description:
      'Delectus sunt odit at voluptatum necessitatibus id enim veritatis. Cum perspiciatis dolorem aliquid pariatur saepe doloribus culpa ea.',
    id: '16',
  },
  {
    mediaId: 'mediaId 17',
    titleImg: 'titleImg 17',
    mainCategory: '2',
    subCategory: '2',
    mediaType: 'mediaType 17',
    madeAt: '2024-04-12T17:40:51.796Z',
    title: 'The Walking Dead',
    casts: ['Andrew Lincoln', 'Steven Yeun', 'Norman Reedus'],
    genres: ['TV Dramas', 'TV Horror'],
    impressions: ['Ominous'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'nudity'],
    description:
      'Tempore blanditiis ut velit quod corrupti saepe. Aliquid ipsam labore adipisci eveniet eius repudiandae doloribus. Explicabo facilis dolore cupiditate explicabo blanditiis at vel.',
    id: '17',
  },
  {
    mediaId: 'mediaId 18',
    titleImg: 'titleImg 18',
    mainCategory: '3',
    subCategory: '5',
    mediaType: 'mediaType 18',
    madeAt: '2024-07-07T18:37:43.436Z',
    title: 'Men in Black',
    casts: ['Tommy Lee Jones', 'Will Smith', 'Linda Fiorentino'],
    genres: ['Sci-Fi Action', 'Comedy'],
    impressions: ['Adventure', 'Action'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['language', 'suggetive material'],
    description:
      'Fugit voluptates voluptatem blanditiis cumque. Optio reiciendis necessitatibus vero exercitationem eos nisi doloribus esse aperiam. Tenetur fuga eaque quibusdam repellendus labore mollitia. Laborum architecto fuga incidunt iure fugiat dolores quod saepe. Eveniet reprehenderit reprehenderit molestiae doloremque unde quam assumenda repellendus. Blanditiis magni iure reiciendis hic quos.',
    id: '18',
  },
  {
    mediaId: 'mediaId 19',
    titleImg: 'titleImg 19',
    mainCategory: '6',
    subCategory: '3',
    mediaType: 'mediaType 19',
    madeAt: '2024-12-08T20:05:31.432Z',
    title: 'Guardians of the Galaxy',
    casts: ['Chris Pratt', 'Zoe Saldana', 'Dave Bautista'],
    genres: ['Sci-Fi Action', 'Comedy'],
    impressions: ['Sci-Fi Action', 'Comedy'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['language', 'violence'],
    description:
      'Dolores consectetur esse repellendus. Numquam nobis accusamus quis delectus laborum hic.',
    id: '19',
  },
  {
    mediaId: 'mediaId 20',
    titleImg: 'titleImg 20',
    mainCategory: '7',
    subCategory: '8',
    mediaType: 'mediaType 20',
    madeAt: '2025-03-05T01:39:19.527Z',
    title: 'Black Mirror',
    casts: ['Awkwafina', 'Peter Capaldi', 'Asim Chaudhry'],
    genres: ['TV Dramas', 'British', 'Sci-Fi TV'],
    impressions: ['Mind-Bending', 'Ominous'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'nudity', 'sex', 'smoking'],
    description: 'Illo tempore odit. Dignissimos mollitia ut quae sint sit.',
    id: '20',
  },
  {
    mediaId: 'mediaId 21',
    titleImg: 'titleImg 21',
    mainCategory: '2',
    subCategory: '5',
    mediaType: 'mediaType 21',
    madeAt: '2025-02-07T23:16:09.287Z',
    title: 'Stranger Things',
    casts: ['Winona Ryder', 'David Harbour', 'Finn Wolfhard'],
    genres: ['TV Dramas', 'Sci-Fi TV', 'TV Horror'],
    impressions: ['Ominous', 'Nostalgic', 'Scary'],
    ratingSymbol: 'TV-14',
    ratingDetails: ['disturbing images', 'fear'],
    description:
      'Iste sequi consequatur enim adipisci dolor sint eveniet minus nemo. Nostrum unde sint eum maxime accusamus. Unde rerum reprehenderit error. Natus magnam porro libero quos sapiente. Reprehenderit sit non at. Rerum praesentium fugiat fugit est expedita laudantium.',
    id: '21',
  },
  {
    mediaId: 'mediaId 22',
    titleImg: 'titleImg 22',
    mainCategory: '9',
    subCategory: '3',
    mediaType: 'mediaType 22',
    madeAt: '2024-06-13T00:35:33.804Z',
    title: 'Hardcore Henry',
    casts: ['Ilya Naishuller', 'Sharlto Copley', 'Danila Kozlovsky'],
    genres: ['Sci-Fi Action'],
    impressions: ['Adventure', 'Action'],
    ratingSymbol: 'R',
    ratingDetails: ['blood', 'violence', 'language'],
    description:
      'Ratione nesciunt atque modi eligendi laudantium quis. Possimus laboriosam fugiat numquam illum ut beatae nesciunt vero tempore. Consequuntur cupiditate fugit perspiciatis maxime reiciendis cum rerum.',
    id: '22',
  },
  {
    mediaId: 'mediaId 23',
    titleImg: 'titleImg 23',
    mainCategory: '2',
    subCategory: '2',
    mediaType: 'mediaType 23',
    madeAt: '2024-05-29T02:50:43.573Z',
    title: 'Sicario Day of the Soldado',
    casts: ['Benicio Del Toro', 'Josh Brolin', 'Isabel Merced'],
    genres: ['Drama Movies', 'Action', 'Adventure'],
    impressions: ['Violent', 'Dark'],
    ratingSymbol: 'R',
    ratingDetails: ['strong violence', 'bloody images'],
    description:
      'Quaerat nisi autem. Voluptate suscipit dolore pariatur consectetur quasi. Deserunt molestias sapiente quia ut. Doloribus expedita nemo quam laudantium quaerat unde. Soluta cupiditate minus optio officia nobis ea. Provident eligendi quos fugit cupiditate voluptatum ducimus rem.',
    id: '23',
  },
  {
    mediaId: 'mediaId 24',
    titleImg: 'titleImg 24',
    mainCategory: '1',
    subCategory: '5',
    mediaType: 'mediaType 24',
    madeAt: '2024-05-12T01:39:03.080Z',
    title: 'Dark',
    casts: ['Louis Hofmann', 'Oliver Masucci', 'Jordis Triebel'],
    genres: ['TV Dramas', 'German', 'Sci-Fi TV'],
    impressions: ['Mind-Bending', 'Chilling', 'Ominous'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'nudity', 'smoking'],
    description:
      'Iste praesentium illo explicabo quibusdam voluptatibus explicabo. Nisi iusto enim repellat ipsum dolor. Soluta beatae dolorum saepe. Occaecati maxime quis sequi impedit nostrum sit consectetur.',
    id: '24',
  },
  {
    mediaId: 'mediaId 25',
    titleImg: 'titleImg 25',
    mainCategory: '2',
    subCategory: '5',
    mediaType: 'mediaType 25',
    madeAt: '2024-04-26T00:03:24.579Z',
    title: 'The Truman Show',
    casts: ['Jim Carrey', 'Laura Linney', 'Ed Harris'],
    genres: ['Comedy', 'Drama'],
    impressions: ['Humorous', 'Psychological'],
    ratingSymbol: 'PG',
    ratingDetails: ['thematic elements', 'mild language'],
    description:
      'Aliquam quidem nemo vel at odit illo eaque. Quod quisquam id quos possimus nisi.',
    id: '25',
  },
  {
    mediaId: 'mediaId 26',
    titleImg: 'titleImg 26',
    mainCategory: '2',
    subCategory: '5',
    mediaType: 'mediaType 26',
    madeAt: '2024-03-14T16:46:36.676Z',
    title: 'Apollo 13',
    casts: ['Tom Hanks', 'Kevin Bacon', 'Bill Paxton'],
    genres: ['Classic Movies', 'Drama movies'],
    impressions: ['Inspiring', 'Suspenseful', 'Emotional'],
    ratingSymbol: 'PG',
    ratingDetails: ['language', 'Suspense'],
    description:
      'Repudiandae quia accusamus distinctio temporibus laboriosam. Perferendis accusamus fugit magnam. Ipsa saepe fugit esse minus.',
    id: '26',
  },
  {
    mediaId: 'mediaId 27',
    titleImg: 'titleImg 27',
    mainCategory: '2',
    subCategory: '1',
    mediaType: 'mediaType 27',
    madeAt: '2024-06-11T10:37:36.397Z',
    title: 'Prison Playbook',
    casts: ['Park Hae-soo', 'Jung Kyung-ho', 'Jung Soo-jung'],
    genres: ['TV Dramas', 'Korean'],
    impressions: ['Witty', 'Gritty', 'Emotional'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'smoking'],
    description:
      'Voluptas similique corrupti reprehenderit modi atque inventore. Quaerat et dolorum unde eius.',
    id: '27',
  },
  {
    mediaId: 'mediaId 28',
    titleImg: 'titleImg 28',
    mainCategory: '1',
    subCategory: '7',
    mediaType: 'mediaType 28',
    madeAt: '2024-05-13T20:04:41.942Z',
    title: 'Star Trek Beyond',
    casts: ['Chris Pine', 'Zachary Quinto', 'Zoe Saldana'],
    genres: ['Sci-Fi Movies', 'Action', 'Adventure'],
    impressions: ['Exciting'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['action', 'violence'],
    description:
      'Iure vero odit facilis repellendus cum tempore. Enim dolor necessitatibus quo reprehenderit. Doloremque vitae incidunt sit voluptate. Quisquam quo veniam esse velit nulla voluptate deserunt ab error. Veritatis voluptatibus minima placeat expedita quae ut.',
    id: '28',
  },
  {
    mediaId: 'mediaId 29',
    titleImg: 'titleImg 29',
    mainCategory: '9',
    subCategory: '3',
    mediaType: 'mediaType 29',
    madeAt: '2024-03-17T13:49:50.894Z',
    title: 'Mindhunter',
    casts: ['Jonathan Groff', 'Holt McCallany', 'Anna Torv'],
    genres: ['TV Dramas', 'TV Shows'],
    impressions: ['Chilling', 'Psychological'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'smoking', 'suicide'],
    description:
      'Possimus delectus rem maiores est quis unde a dolorem vel. Sint totam excepturi esse modi nihil reprehenderit laudantium. Quae at occaecati ullam doloremque tempore dicta. Facilis eum voluptate tenetur sed corrupti necessitatibus temporibus qui sit. Quisquam ea numquam corporis non consectetur dolor amet excepturi in.',
    id: '29',
  },
  {
    mediaId: 'mediaId 30',
    titleImg: 'titleImg 30',
    mainCategory: '4',
    subCategory: '3',
    mediaType: 'mediaType 30',
    madeAt: '2025-02-03T01:09:14.971Z',
    title: 'Bright',
    casts: ['Will Smith', 'Joel Edgerton', 'Noomi Repace'],
    genres: ['Action', 'Adventure'],
    impressions: ['Violent', 'Gritty'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'nudity', 'smoking'],
    description:
      'Placeat atque tempore dolorem aliquam deserunt delectus. Culpa nobis expedita aliquam a quo harum maiores excepturi.',
    id: '30',
  },
  {
    mediaId: 'mediaId 31',
    titleImg: 'titleImg 31',
    mainCategory: '6',
    subCategory: '2',
    mediaType: 'mediaType 31',
    madeAt: '2024-08-13T16:34:52.245Z',
    title: 'The OA',
    casts: ['Brit Marling', 'Jason Isaacs', 'Emory Cohen'],
    genres: ['TV Dramas', 'Sci-Fi TV'],
    impressions: ['Mind-Bending', 'Intimate'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'nudity', 'sex', 'smoking'],
    description:
      'Officiis enim culpa dolor. Facere deserunt reiciendis reprehenderit. Possimus expedita illum earum velit natus occaecati veritatis. Enim odit quo veniam officia voluptates eos praesentium iste odit.',
    id: '31',
  },
  {
    mediaId: 'mediaId 32',
    titleImg: 'titleImg 32',
    mainCategory: '9',
    subCategory: '2',
    mediaType: 'mediaType 32',
    madeAt: '2024-05-08T14:23:57.665Z',
    title: "Don't Look Up",
    casts: ['Leonardo DiCaprio', 'Jennifer Lawrence', 'Meryl Streep'],
    genres: ['Sci-Fi Movies', 'Satires', 'Drama Movies'],
    impressions: ['Provocative', 'Witty'],
    ratingSymbol: 'R',
    ratingDetails: ['language', 'graphic nudity', 'drug content'],
    description:
      'Maxime ex quisquam ut cum minima. Occaecati perspiciatis reiciendis totam ipsum. Officiis praesentium quaerat eveniet praesentium quas laborum. Vitae ullam unde cum ipsam laboriosam dignissimos velit. Aspernatur assumenda explicabo nesciunt quos unde.',
    id: '32',
  },
  {
    mediaId: 'mediaId 33',
    titleImg: 'titleImg 33',
    mainCategory: '2',
    subCategory: '9',
    mediaType: 'mediaType 33',
    madeAt: '2024-06-23T12:43:44.010Z',
    title: '72 Dangerous Animals Latin America',
    casts: ['Bob Bribane'],
    genres: ['Australian', 'Nature', 'Ecology', 'Science'],
    impressions: ['Investigative', 'Suspenseful'],
    ratingSymbol: 'TV-14',
    ratingDetails: ['fear'],
    description:
      'Dolorum id perspiciatis dolore aliquam eius molestiae ex eum. Id iusto nobis explicabo. Doloremque rem voluptatibus dicta natus nostrum non nisi autem voluptates. Mollitia id ullam voluptatem quidem iure nihil veniam. Blanditiis modi architecto debitis. Corrupti soluta fugit.',
    id: '33',
  },
  {
    mediaId: 'mediaId 34',
    titleImg: 'titleImg 34',
    mainCategory: '7',
    subCategory: '9',
    mediaType: 'mediaType 34',
    madeAt: '2024-10-02T15:27:15.407Z',
    title: 'okja',
    casts: ['Tilda Swinton', 'Jake Gyllenhaal', 'An Seo-hyun'],
    genres: ['Satires', 'Drama Movies', 'Comedy'],
    impressions: ['Offbeat', 'Emotional'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'smoking'],
    description:
      'Cupiditate accusantium incidunt. Eaque error ullam quas nostrum neque ipsum soluta. Incidunt occaecati perferendis vel facere vitae.',
    id: '34',
  },
  {
    mediaId: 'mediaId 35',
    titleImg: 'titleImg 35',
    mainCategory: '3',
    subCategory: '2',
    mediaType: 'mediaType 35',
    madeAt: '2024-05-04T11:42:51.181Z',
    title: 'Manhunt: Unabomber',
    casts: ['Sam Worthington', 'Paul Bettany', 'Jeremy Bobb'],
    genres: ['Drama', 'True Crime'],
    impressions: ['Violent', 'Suspenseful'],
    ratingSymbol: 'TV-14',
    ratingDetails: ['language', 'violence'],
    description:
      'Esse tempora temporibus vitae. Debitis iusto quaerat corporis sapiente voluptate ut quisquam ea sequi.',
    id: '35',
  },
  {
    mediaId: 'mediaId 36',
    titleImg: 'titleImg 36',
    mainCategory: '9',
    subCategory: '7',
    mediaType: 'mediaType 36',
    madeAt: '2024-12-05T07:05:56.224Z',
    title: 'Van Helsing',
    casts: ['Kelly Overton', 'Jonathan Scarfe'],
    genres: ['TV Dramas', 'Canadian', 'TV Action'],
    impressions: ['Violent', 'Dark', 'Exciting'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'nudity', 'smoking'],
    description:
      'Repellendus libero earum illo libero. Excepturi et laborum quia in distinctio aliquid. Nemo quo reiciendis fuga temporibus distinctio. Sapiente nemo ipsam totam maxime modi. At quas dolor inventore illo voluptates voluptatum.',
    id: '36',
  },
  {
    mediaId: 'mediaId 37',
    titleImg: 'titleImg 37',
    mainCategory: '8',
    subCategory: '9',
    mediaType: 'mediaType 37',
    madeAt: '2025-02-18T02:23:11.537Z',
    title: 'Miami Vice',
    casts: ['Colin Farrell', 'Jamie Foxx', 'Gong Li'],
    genres: ['Action', 'Crime'],
    impressions: ['Violent'],
    ratingSymbol: 'R',
    ratingDetails: ['language', 'violence'],
    description:
      'Facilis natus aperiam exercitationem qui impedit laudantium nam suscipit. Quos dicta molestiae perferendis. Suscipit fugiat laboriosam provident id praesentium architecto ex blanditiis. Optio similique debitis nisi impedit quibusdam eligendi deserunt. Fugiat totam laboriosam voluptatem facere. Illum est veniam quae dicta doloremque eligendi.',
    id: '37',
  },
  {
    mediaId: 'mediaId 38',
    titleImg: 'titleImg 38',
    mainCategory: '2',
    subCategory: '1',
    mediaType: 'mediaType 38',
    madeAt: '2024-06-20T20:07:31.648Z',
    title: 'The Mist',
    casts: ['Morgan Spector', 'Alyssa Sutherland', 'Gus Birney'],
    genres: ['TV Dramas', 'Sci-Fi TV'],
    impressions: ['Omnious', 'Scary', 'Dark'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'nudity', 'violence'],
    description:
      'Nulla amet dolores. Voluptas perspiciatis eaque. Molestiae repudiandae unde at numquam eligendi similique. Quibusdam minima odit sit aliquam libero.',
    id: '38',
  },
  {
    mediaId: 'mediaId 39',
    titleImg: 'titleImg 39',
    mainCategory: '8',
    subCategory: '5',
    mediaType: 'mediaType 39',
    madeAt: '2025-01-02T09:08:57.476Z',
    title: 'Cloverfield',
    casts: ['Michael Stahl', 'Odette Yustman'],
    genres: ['Horror', 'Action'],
    impressions: ['Omnious', 'Scary'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['violence', 'terror', 'nudity'],
    description:
      'Debitis quod temporibus saepe aperiam iste quis illo. Saepe ducimus repellat assumenda asperiores dolores. Animi minus illum dolorem veritatis id mollitia officia consequatur totam.',
    id: '39',
  },
  {
    mediaId: 'mediaId 40',
    titleImg: 'titleImg 40',
    mainCategory: '4',
    subCategory: '5',
    mediaType: 'mediaType 40',
    madeAt: '2024-09-23T13:27:14.259Z',
    title: 'Cars 3',
    casts: ['Owen Wilson', 'Nathan Fillion', 'Kerry Washington'],
    genres: ['Family', 'Sport'],
    impressions: ['Comedy', 'Adventurous', 'Exciting'],
    ratingSymbol: 'G',
    ratingDetails: ['action', 'comedy'],
    description:
      'Eius facere facilis quam itaque occaecati. Veritatis odit excepturi. In doloremque doloremque aperiam unde molestiae nesciunt cum tenetur.',
    id: '40',
  },
  {
    mediaId: 'mediaId 41',
    titleImg: 'titleImg 41',
    mainCategory: '6',
    subCategory: '2',
    mediaType: 'mediaType 41',
    madeAt: '2024-10-26T19:46:26.962Z',
    title: 'Dawn of the Planet of the Apes',
    casts: ['Andy Serkis', 'Jason Clarke', 'Gary Oldman'],
    genres: ['Action', 'Sci-Fi Movie'],
    impressions: ['Provocative', 'Violent', 'Scary'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['violence', 'scariness', 'language'],
    description:
      'Assumenda delectus facilis modi expedita quos laborum. Nihil nostrum voluptate consequuntur rem nobis esse libero alias.',
    id: '41',
  },
  {
    mediaId: 'mediaId 42',
    titleImg: 'titleImg 42',
    mainCategory: '5',
    subCategory: '8',
    mediaType: 'mediaType 42',
    madeAt: '2025-02-01T05:30:07.946Z',
    title: 'Moon',
    casts: ['Sam Rockwell', 'Dominique McElligott', 'Kaya Scodelario'],
    genres: ['Sci-Fi', 'Mystery'],
    impressions: ['Frightening', 'Intense'],
    ratingSymbol: 'R',
    ratingDetails: ['blood', 'threat', 'tension'],
    description:
      'Iure doloribus provident atque mollitia. Eius tenetur reprehenderit. Exercitationem minus natus eligendi quo repellendus animi.',
    id: '42',
  },
  {
    mediaId: 'mediaId 43',
    titleImg: 'titleImg 43',
    mainCategory: '9',
    subCategory: '9',
    mediaType: 'mediaType 43',
    madeAt: '2025-02-08T09:13:34.662Z',
    title: 'The 5th Wave',
    casts: ['Chloe Grace', 'Nick Robinson', 'Ron Livingston'],
    genres: ['Sci-Fi Movies', 'Action', 'Adventure'],
    impressions: ['Exciting'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['violence', 'destruction', 'language'],
    description:
      'Sint explicabo ratione animi dignissimos autem quidem eveniet. Ipsa eligendi necessitatibus quasi magni ut doloremque adipisci reiciendis. Facere excepturi itaque tempore beatae molestias suscipit neque temporibus.',
    id: '43',
  },
  {
    mediaId: 'mediaId 44',
    titleImg: 'titleImg 44',
    mainCategory: '2',
    subCategory: '3',
    mediaType: 'mediaType 44',
    madeAt: '2024-12-22T08:55:15.842Z',
    title: 'Angels & Demons',
    casts: ['Tom Hanks', 'Ewan McGregor', 'Ayelet Zurer'],
    genres: ['Thriller', 'Mystery'],
    impressions: ['Violent'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['blood', 'gore', 'graphic'],
    description:
      'Dolore numquam adipisci laudantium assumenda doloremque architecto numquam. Impedit laborum asperiores mollitia impedit. Et odit beatae similique fugiat quasi quis. Iure maiores cumque veniam consectetur ea impedit veniam.',
    id: '44',
  },
  {
    mediaId: 'mediaId 45',
    titleImg: 'titleImg 45',
    mainCategory: '8',
    subCategory: '3',
    mediaType: 'mediaType 45',
    madeAt: '2024-07-10T18:52:13.454Z',
    title: 'Money Heist',
    casts: ['Ursula Corbero', 'Alvaro Morte', 'Itziar Ituno'],
    genres: ['Spanish', 'Crime', 'Thriller'],
    impressions: ['Suspenseful', 'Exciting'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'nudity', 'smoking', 'violence'],
    description:
      'Vel dolores alias quaerat beatae sunt similique occaecati. Magnam vel veritatis. Cumque numquam ad veniam ullam omnis labore nihil. Veniam odio quidem veniam iste nisi impedit. Odio doloribus impedit inventore.',
    id: '45',
  },
  {
    mediaId: 'mediaId 46',
    titleImg: 'titleImg 46',
    mainCategory: '8',
    subCategory: '9',
    mediaType: 'mediaType 46',
    madeAt: '2025-01-20T18:48:19.919Z',
    title: 'My Name',
    casts: ['Han So-hee', 'Park Hee-soon', 'Ahn Bo-hyun'],
    genres: ['Korean', 'TV Action', 'Adventure'],
    impressions: ['Dark', 'Suspenseful'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'sex', 'smoking', 'substances'],
    description:
      'Quis veritatis excepturi optio. Distinctio quod illum ea consequatur expedita commodi molestiae. Illum ipsum ex quasi ratione enim. Consequatur doloribus porro. Architecto laudantium soluta non.',
    id: '46',
  },
  {
    mediaId: 'mediaId 47',
    titleImg: 'titleImg 47',
    mainCategory: '2',
    subCategory: '4',
    mediaType: 'mediaType 47',
    madeAt: '2024-10-26T23:43:54.822Z',
    title: 'Damsel',
    casts: ['Millie Bobby', 'Ray Winstone', 'Robin Wright'],
    genres: ['Action', 'Adventure'],
    impressions: ['Rousing', 'Imaginative', 'Suspenseful'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['violence', 'action', 'blood'],
    description:
      'Omnis illo quibusdam. Minus facilis a hic numquam natus quaerat aliquam aspernatur iste. Dolorum debitis nisi. Pariatur culpa quia autem quae debitis soluta quod. Expedita non porro autem. Repellendus eum officia eveniet aspernatur accusamus nesciunt harum id tenetur.',
    id: '47',
  },
  {
    mediaId: 'mediaId 48',
    titleImg: 'titleImg 48',
    mainCategory: '4',
    subCategory: '4',
    mediaType: 'mediaType 48',
    madeAt: '2025-01-28T00:21:01.122Z',
    title: 'Ballerina',
    casts: ['Jun Jong-seo', 'Kim Ji-hun', 'Park Yu-rim'],
    genres: ['Korean', 'Action', 'Adventure'],
    impressions: ['Violent'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'sex', 'smoking', 'suicide'],
    description:
      'Id dolorem quaerat quia. Quis eligendi corrupti ratione debitis deleniti quaerat ad porro mollitia. Tempore quam iure rem et molestias eligendi nemo libero.',
    id: '48',
  },
  {
    mediaId: 'mediaId 49',
    titleImg: 'titleImg 49',
    mainCategory: '3',
    subCategory: '4',
    mediaType: 'mediaType 49',
    madeAt: '2024-05-01T05:30:39.509Z',
    title: 'Rebel Moon',
    casts: ['Sofia Boutella', 'Djimon Hounsou', 'Ed Skrein'],
    genres: ['Sci-Fi Movies', 'Action', 'Adventure'],
    impressions: ['Exciting'],
    ratingSymbol: 'R',
    ratingDetails: ['gore', 'violence', 'nudity', 'language'],
    description:
      'Asperiores perspiciatis suscipit ea. Inventore voluptas delectus quidem nesciunt neque quod repellendus numquam. Corrupti non iure enim. Corporis unde qui ipsa. Dolores dolorem voluptatem temporibus corrupti dolor dolor odit perspiciatis animi.',
    id: '49',
  },
  {
    mediaId: 'mediaId 50',
    titleImg: 'titleImg 50',
    mainCategory: '2',
    subCategory: '9',
    mediaType: 'mediaType 50',
    madeAt: '2024-12-29T00:29:55.041Z',
    title: 'EX_MACHINA',
    casts: ['Domhnall Gleeson', 'Oscar Isaac', 'Alicia Vikander'],
    genres: ['Sci-Fi Movies', 'British', 'Drama Movies'],
    impressions: ['Cerebral', 'Psychological', 'Understated'],
    ratingSymbol: 'R',
    ratingDetails: ['nudity', 'language'],
    description:
      'Ratione natus eos. Enim veritatis praesentium illo distinctio natus rem voluptatibus expedita. Quae distinctio voluptatibus minus quod magnam quo. Labore ab dicta labore quasi possimus asperiores voluptatem necessitatibus harum. Dicta voluptas totam similique eius quaerat. Minima sint doloribus fugit asperiores corrupti sed.',
    id: '50',
  },
  {
    mediaId: 'mediaId 51',
    titleImg: 'titleImg 51',
    mainCategory: '7',
    subCategory: '7',
    mediaType: 'mediaType 51',
    madeAt: '2024-09-17T13:02:45.665Z',
    title: 'Arrival',
    casts: ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'],
    genres: ['Sci-Fi Movies', 'Drama Movies'],
    impressions: ['Mind-Bending', 'Cerebral', 'Understated'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['stron language'],
    description:
      'Nam alias voluptatum. Inventore repellendus similique veritatis. Quasi explicabo ipsam inventore amet repudiandae. Officia quaerat dolor corporis dignissimos. Magnam placeat odit eligendi fuga. Quis eaque beatae possimus culpa magni laborum quae.',
    id: '51',
  },
  {
    mediaId: 'mediaId 52',
    titleImg: 'titleImg 52',
    mainCategory: '9',
    subCategory: '4',
    mediaType: 'mediaType 52',
    madeAt: '2025-02-16T22:51:31.868Z',
    title: 'Stranger',
    casts: ['Cho Seung-woo', 'Doona Bae', 'Jeon Hey-jin'],
    genres: ['TV Dramas', 'Korean', 'Crime'],
    impressions: ['Cerebral', 'Suspenseful'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'smoking', 'violence'],
    description:
      'Expedita veniam eaque eius recusandae laudantium dignissimos dicta. Amet velit quidem libero. Alias mollitia quo.',
    id: '52',
  },
  {
    mediaId: 'mediaId 53',
    titleImg: 'titleImg 53',
    mainCategory: '1',
    subCategory: '7',
    mediaType: 'mediaType 53',
    madeAt: '2024-10-19T14:09:56.151Z',
    title: 'The Glory',
    casts: ['Song Hye-kyo', 'Lee Do-hyun', 'Lim Ji-yeon'],
    genres: ['TV Dramas', 'Korean'],
    impressions: ['Dark'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'sex', 'smoking'],
    description: 'Nisi blanditiis quia. Rem dicta accusamus officia.',
    id: '53',
  },
  {
    mediaId: 'mediaId 54',
    titleImg: 'titleImg 54',
    mainCategory: '7',
    subCategory: '6',
    mediaType: 'mediaType 54',
    madeAt: '2024-05-25T05:21:24.409Z',
    title: '3 Body Problem',
    casts: ['Jess Hong', 'Liam Cunningham', 'Eiza Gonzalez'],
    genres: ['TV Dramas', 'Sci-Fi TV'],
    impressions: ['Mind-Bending', 'Cerebral', 'Imaginative'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'nudity', 'smoking'],
    description:
      'Deserunt laborum iusto expedita accusantium vel. Vitae repudiandae placeat error. Minima nesciunt ex deleniti ullam nam nulla. Expedita doloremque harum similique recusandae iure eos autem impedit eligendi. Placeat doloremque quae nisi perspiciatis.',
    id: '54',
  },
  {
    mediaId: 'mediaId 55',
    titleImg: 'titleImg 55',
    mainCategory: '6',
    subCategory: '9',
    mediaType: 'mediaType 55',
    madeAt: '2025-03-08T14:48:56.093Z',
    title: 'Shaft',
    casts: ['Samuel Jackson', 'Jessie Usher', 'Regina Hall'],
    genres: ['Comedy', 'Action', 'Adventure'],
    impressions: ['Exciting'],
    ratingSymbol: 'R',
    ratingDetails: ['language', 'violence', 'drug'],
    description:
      'Neque possimus facilis modi iure corrupti distinctio reprehenderit dignissimos perspiciatis. Eaque et magni possimus repudiandae pariatur distinctio. Adipisci officia necessitatibus nostrum repudiandae possimus. Ab possimus maiores dolor quaerat illo. Repudiandae totam nobis cupiditate libero quia modi. A ad a quis.',
    id: '55',
  },
  {
    mediaId: 'mediaId 56',
    titleImg: 'titleImg 56',
    mainCategory: '5',
    subCategory: '3',
    mediaType: 'mediaType 56',
    madeAt: '2024-09-28T20:55:21.108Z',
    title: 'Now you see me 2',
    casts: ['Jesse Eisenberg', 'Mark Ruffalo', 'Woody Harrelson'],
    genres: ['Mystery', 'Action', 'Adventure'],
    impressions: ['Imaginative', 'Suspenseful', 'Exciting'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['violence', 'language'],
    description:
      'Hic facilis sed tempore et dignissimos dolorum odit. Ducimus doloremque totam ipsa distinctio corrupti quod. Reprehenderit omnis ipsa perspiciatis atque quis esse totam totam aspernatur.',
    id: '56',
  },
  {
    mediaId: 'mediaId 57',
    titleImg: 'titleImg 57',
    mainCategory: '4',
    subCategory: '6',
    mediaType: 'mediaType 57',
    madeAt: '2024-10-03T13:17:43.263Z',
    title: 'Ozark',
    casts: ['Jason Bateman', 'Laura Linney', 'Sofia Hublitz'],
    genres: ['TV Dramas', 'Crime TV', 'TV Thrillers'],
    impressions: ['Omnious', 'Dark'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'nudity', 'sex', 'smoking'],
    description:
      'Facilis veritatis at et harum. Explicabo porro quis accusamus impedit deleniti reiciendis inventore labore reprehenderit.',
    id: '57',
  },
  {
    mediaId: 'mediaId 58',
    titleImg: 'titleImg 58',
    mainCategory: '1',
    subCategory: '6',
    mediaType: 'mediaType 58',
    madeAt: '2025-02-02T11:52:27.678Z',
    title: 'Leave the World Behind',
    casts: ['Julia Roberts', 'Mahershala Ali', 'Ethan Hawke'],
    genres: ['Drama Movies', 'Thriller Movies'],
    impressions: ['Chilling', 'Ominous', 'Psychological'],
    ratingSymbol: 'R',
    ratingDetails: ['language', 'drug use', 'blood'],
    description:
      'Non officiis at quas nostrum natus itaque amet harum aperiam. Culpa incidunt beatae a officiis repudiandae quaerat tempora. Eveniet dolore in sunt a hic maiores velit quisquam fuga. Non quo tempora voluptates possimus quia qui est voluptates. Vel omnis non quae repellat quibusdam amet quisquam aspernatur accusantium. Consequuntur illo quod quo hic.',
    id: '58',
  },
  {
    mediaId: 'mediaId 59',
    titleImg: 'titleImg 59',
    mainCategory: '6',
    subCategory: '9',
    mediaType: 'mediaType 59',
    madeAt: '2024-09-24T11:15:50.898Z',
    title: 'Fury',
    casts: ['Brad Pitt', 'Shia LaBeouf', 'Logan Lerman'],
    genres: ['Military Movies', 'Drama Movies', 'Action'],
    impressions: ['Gritty'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language'],
    description:
      'Necessitatibus voluptates iusto placeat. Optio officia officiis doloribus provident officiis ullam eius optio. Ipsam corporis voluptatum ipsum fugit minima eius asperiores quas ipsam. Molestias labore dolore similique non in modi maxime. Tenetur dolor soluta quia distinctio sequi debitis.',
    id: '59',
  },
  {
    mediaId: 'mediaId 60',
    titleImg: 'titleImg 60',
    mainCategory: '9',
    subCategory: '3',
    mediaType: 'mediaType 60',
    madeAt: '2024-04-21T16:54:16.641Z',
    title: 'A Man Called Otto',
    casts: ['Tom Hanks', 'Mariana Trevino', 'Rachell Keller'],
    genres: ['Drama Movies', 'Tearjerker', 'Comedy'],
    impressions: ['Heartfelt', 'Emotional'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['suicide', 'language'],
    description:
      'Soluta consequatur earum omnis facere voluptates quasi cupiditate. Distinctio pariatur doloremque autem perferendis quasi atque. Quod est quia ipsum. A dolores vitae nobis quibusdam eaque beatae. Eum provident eum voluptatum nostrum ipsa optio. Voluptatibus sed ut eaque.',
    id: '60',
  },
  {
    mediaId: 'mediaId 61',
    titleImg: 'titleImg 61',
    mainCategory: '1',
    subCategory: '9',
    mediaType: 'mediaType 61',
    madeAt: '2024-04-05T18:37:34.323Z',
    title: 'Whiplash',
    casts: ['Miles Teller', 'J.K.Simmons', 'Paul Reiser'],
    genres: ['Music', 'Drama Movies'],
    impressions: ['Psychological'],
    ratingSymbol: 'R',
    ratingDetails: ['language'],
    description:
      'Numquam maxime autem explicabo rerum odio vitae molestiae. Autem neque nam quo maiores error. Ex aliquid mollitia. Provident ex non minus blanditiis quae vitae quam consequatur rerum. Quia doloremque voluptatem adipisci vel at nobis ad. Cumque modi hic libero.',
    id: '61',
  },
  {
    mediaId: 'mediaId 62',
    titleImg: 'titleImg 62',
    mainCategory: '2',
    subCategory: '5',
    mediaType: 'mediaType 62',
    madeAt: '2024-09-10T20:12:21.738Z',
    title: 'Extraction 2',
    casts: ['Chris Hemsworth', 'Golshifteh Farahani'],
    genres: ['Action', 'Adventure'],
    impressions: ['Explosive', 'Violent', 'Gritty'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language'],
    description:
      'Quisquam possimus esse id molestias. Cumque magni laboriosam. Hic veniam id labore nisi totam distinctio. Debitis maiores consequatur quod ut eveniet amet ipsam.',
    id: '62',
  },
  {
    mediaId: 'mediaId 63',
    titleImg: 'titleImg 63',
    mainCategory: '3',
    subCategory: '5',
    mediaType: 'mediaType 63',
    madeAt: '2024-06-15T07:17:17.271Z',
    title: 'Hitman',
    casts: ['Timothy Olyphant', 'Dougray Scott', 'Olga Kurylenko'],
    genres: ['Action', 'Adventure'],
    impressions: ['Violent', 'Exciting'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language', 'nudity'],
    description:
      'Architecto corporis est. Architecto laudantium eos. Delectus dolorem minima voluptatem facilis vero ab voluptate. Accusamus praesentium labore voluptatum voluptatem nesciunt. Esse similique voluptatem debitis voluptates. Officia ab laudantium alias et.',
    id: '63',
  },
  {
    mediaId: 'mediaId 64',
    titleImg: 'titleImg 64',
    mainCategory: '7',
    subCategory: '5',
    mediaType: 'mediaType 64',
    madeAt: '2025-02-02T15:21:09.320Z',
    title: 'Resident Evil',
    casts: ['Milla Jovovich', 'Michelle Rodriguez', 'Colin Salmon'],
    genres: ['Sci-Fi Movies', 'Horror Movies', 'Action'],
    impressions: ['Violent'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language', 'nudity'],
    description:
      'Nihil maiores neque quo doloribus. Animi quam ea enim tempore illum repellat ea magni ab.',
    id: '64',
  },
  {
    mediaId: 'mediaId 65',
    titleImg: 'titleImg 65',
    mainCategory: '7',
    subCategory: '9',
    mediaType: 'mediaType 65',
    madeAt: '2024-08-15T04:31:21.191Z',
    title: 'The Accountant',
    casts: ['Ben Affleck', 'Anna Kendrick', 'J.K.Simmons'],
    genres: ['Action', 'Adventure'],
    impressions: ['Exciting'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language'],
    description:
      'Porro non architecto hic possimus animi totam possimus nesciunt corrupti. Optio quod facilis ipsum dolores est doloribus nesciunt.',
    id: '65',
  },
  {
    mediaId: 'mediaId 66',
    titleImg: 'titleImg 66',
    mainCategory: '8',
    subCategory: '2',
    mediaType: 'mediaType 66',
    madeAt: '2024-03-30T23:27:10.691Z',
    title: 'Riddick',
    casts: ['Vin Diesel', 'Jordi Molla', 'Matt Nable'],
    genres: ['Sci-Fi Movies', 'Monster Movies'],
    impressions: ['Violent'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language', 'nudity'],
    description:
      'Pariatur architecto suscipit ad officiis dignissimos quo saepe quam reiciendis. Dolorem quidem occaecati repellendus est maiores adipisci eaque repellat. Reprehenderit voluptatibus tempora dignissimos nisi.',
    id: '66',
  },
  {
    mediaId: 'mediaId 67',
    titleImg: 'titleImg 67',
    mainCategory: '7',
    subCategory: '6',
    mediaType: 'mediaType 67',
    madeAt: '2024-11-20T05:15:41.992Z',
    title: 'Looper',
    casts: ['Bruce Willis', 'Joseph Gordon', 'Emily Blunt'],
    genres: ['Sci-Fi Movies', 'Action', 'Adventure'],
    impressions: ['Mind-Bending', 'Dark'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language', 'nudity'],
    description:
      'Quisquam culpa commodi eius vel voluptatem. Quam ea necessitatibus aut officia mollitia. Quo excepturi veniam ab. Nemo cum numquam.',
    id: '67',
  },
  {
    mediaId: 'mediaId 68',
    titleImg: 'titleImg 68',
    mainCategory: '8',
    subCategory: '9',
    mediaType: 'mediaType 68',
    madeAt: '2024-11-18T08:18:40.246Z',
    title: 'Hellboy',
    casts: ['David Harbour', 'Milla Jovovich', 'Ian McShane'],
    genres: ['Monster Movies', 'Action', 'Adventure'],
    impressions: ['Violent', 'Exciting'],
    ratingSymbol: 'R',
    ratingDetails: ['blood', 'violence', 'gore', 'language'],
    description:
      'Voluptate magnam iusto id. Delectus cumque quos earum recusandae ex veritatis tempora. Quaerat ea molestiae architecto ipsa sint consequatur similique saepe aliquid. Quisquam voluptate dicta. Quam laboriosam voluptate hic aspernatur eos numquam praesentium. Odit maxime nesciunt sed.',
    id: '68',
  },
  {
    mediaId: 'mediaId 69',
    titleImg: 'titleImg 69',
    mainCategory: '4',
    subCategory: '4',
    mediaType: 'mediaType 69',
    madeAt: '2025-02-26T17:52:45.397Z',
    title: 'Inglourious Basterds',
    casts: ['Brad Pitt', 'Melanie Laurent', 'Christoph Waltz'],
    genres: ['Classic Movies', 'Action', 'Adventure'],
    impressions: ['Violent', 'Suspenseful'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language'],
    description:
      'Enim ipsa dolores omnis ipsum optio unde commodi accusantium. Voluptatibus occaecati tenetur molestias. Autem eum veniam asperiores quasi.',
    id: '69',
  },
  {
    mediaId: 'mediaId 70',
    titleImg: 'titleImg 70',
    mainCategory: '1',
    subCategory: '4',
    mediaType: 'mediaType 70',
    madeAt: '2025-03-04T12:02:47.245Z',
    title: 'Mindhunter',
    casts: ['Jonathan Groff', 'Holt McCallany', 'Anna Torv'],
    genres: ['TV Dramas', 'Mysteries'],
    impressions: ['Chilling', 'Psychological'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'nudity', 'smoking'],
    description:
      'Numquam atque saepe saepe debitis dolores labore ex. Nobis autem aspernatur. Hic nulla maxime. Aut quaerat et repellat ut eos vel.',
    id: '70',
  },
  {
    mediaId: 'mediaId 71',
    titleImg: 'titleImg 71',
    mainCategory: '6',
    subCategory: '8',
    mediaType: 'mediaType 71',
    madeAt: '2025-01-20T22:22:36.126Z',
    title: 'Spectral',
    casts: ['James Badge', 'Emily Mortimer', 'Bruce Greenwood'],
    genres: ['Sci-Fi Movies', 'Military', 'Action'],
    impressions: ['Chilling', 'Ominous', 'Suspenseful'],
    ratingSymbol: 'TV-14',
    ratingDetails: ['fear', 'language', 'vioence'],
    description: 'Ullam esse optio iure in voluptate. A facere iure magnam.',
    id: '71',
  },
  {
    mediaId: 'mediaId 72',
    titleImg: 'titleImg 72',
    mainCategory: '8',
    subCategory: '2',
    mediaType: 'mediaType 72',
    madeAt: '2024-06-22T11:13:48.966Z',
    title: 'Lost',
    casts: ['Matthew Fox', 'Evangeline Lilly', 'Josh Holloway'],
    genres: ['TV Dramas', 'Sci-Fi TV', 'Action', 'Adventure'],
    impressions: ['Emotional', 'Exciting'],
    ratingSymbol: 'TV-14',
    ratingDetails: ['fear', 'language', 'smoking', 'substances'],
    description:
      'Cupiditate totam voluptates ipsum veniam distinctio fugiat dicta iste. Optio repellat vitae at similique sint cumque expedita sit. Porro itaque est dicta aspernatur et consequuntur. Fugit ipsum necessitatibus provident quos at fugit. Est qui tempore illum beatae.',
    id: '72',
  },
  {
    mediaId: 'mediaId 73',
    titleImg: 'titleImg 73',
    mainCategory: '3',
    subCategory: '5',
    mediaType: 'mediaType 73',
    madeAt: '2024-04-07T08:04:18.824Z',
    title: 'Django Unchained',
    casts: ['Jamie Foxx', 'Christoph Waltz', 'Leonardo DiCaprio'],
    genres: ['Drama Movies', 'Westerns'],
    impressions: ['Violent'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language', 'nudity'],
    description: 'Non earum numquam. Voluptas nulla animi nulla suscipit.',
    id: '73',
  },
  {
    mediaId: 'mediaId 74',
    titleImg: 'titleImg 74',
    mainCategory: '4',
    subCategory: '7',
    mediaType: 'mediaType 74',
    madeAt: '2024-08-23T10:21:54.384Z',
    title: 'Edge of Tomorrow',
    casts: ['Tom Cruise', 'Emily Blunt', 'Brendan Gleeson'],
    genres: ['Sci-Fi Movies', 'Military'],
    impressions: ['Explosive', 'Adrenaline', 'Rush', 'Imaginative'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['action', 'violence', 'language'],
    description:
      'Adipisci cum quas et. Minus illum libero repudiandae reprehenderit dignissimos maxime quis molestias. Nihil quis porro accusamus autem qui minima mollitia soluta. Ab quam ipsa repellat velit exercitationem maxime totam veniam. Cupiditate dicta officia veniam quam quod. Vitae dignissimos mollitia error.',
    id: '74',
  },
  {
    mediaId: 'mediaId 75',
    titleImg: 'titleImg 75',
    mainCategory: '7',
    subCategory: '4',
    mediaType: 'mediaType 75',
    madeAt: '2024-09-26T20:33:06.918Z',
    title: 'Green Book',
    casts: ['Viggo Mortensen', 'Mahershala Ali', 'Linda Cardellini'],
    genres: ['Drama Movies', 'Comedy'],
    impressions: ['Sentimental', 'Heartfelt'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['thematic content', 'language', 'smoking'],
    description:
      'Minus eius maxime quas perspiciatis consectetur temporibus similique eum veritatis. Eligendi fugiat minus qui dicta sunt rerum minus laboriosam corporis. Quod voluptate in cum culpa atque est corporis consequuntur. Odio nesciunt inventore laudantium minima perferendis maxime libero.',
    id: '75',
  },
  {
    mediaId: 'mediaId 76',
    titleImg: 'titleImg 76',
    mainCategory: '4',
    subCategory: '5',
    mediaType: 'mediaType 76',
    madeAt: '2024-06-17T06:57:33.455Z',
    title: 'I See You',
    casts: ['Helen Hunt', 'Jon Tenney', 'Judah Lewis'],
    genres: ['Horror Movies', 'Thriller', 'Mystery'],
    impressions: ['Ominous', 'Scary', 'Dark'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language'],
    description:
      'Est ullam quam praesentium. Alias nesciunt molestias laborum tempore. Sapiente fugiat laborum odit eligendi harum suscipit voluptas cumque est. Assumenda voluptatem perspiciatis tempora ipsa odio natus laboriosam magnam adipisci. Repellat impedit ad commodi similique consequuntur facilis.',
    id: '76',
  },
  {
    mediaId: 'mediaId 77',
    titleImg: 'titleImg 77',
    mainCategory: '6',
    subCategory: '6',
    mediaType: 'mediaType 77',
    madeAt: '2024-11-24T11:54:49.032Z',
    title: 'The Adam Project',
    casts: ['Ryan Reynolds', 'Mark Ruffalo', 'Jennifer Garner'],
    genres: ['Family Movies', 'Sci-Fi Movies', 'Comedy'],
    impressions: ['Witty', 'Feel-Good', 'Exciting'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['violence', 'action', 'language'],
    description:
      'Fugit pariatur quo tempore cupiditate velit est magnam quibusdam placeat. Sint nam mollitia fuga enim assumenda aut vitae earum quasi. Magni aspernatur praesentium maxime tenetur esse. Facilis dolor qui dolores assumenda in nobis at expedita saepe. Voluptatum quia sapiente laborum voluptate. Eveniet sapiente saepe facere voluptate ipsum incidunt.',
    id: '77',
  },
  {
    mediaId: 'mediaId 78',
    titleImg: 'titleImg 78',
    mainCategory: '7',
    subCategory: '1',
    mediaType: 'mediaType 78',
    madeAt: '2024-12-01T14:38:17.556Z',
    title: 'Life',
    casts: ['Jake Gyllenhaal', 'Rebecca Ferguson', 'Ryan Reynolds'],
    genres: ['Sci-Fi Movies', 'Horror Movies'],
    impressions: ['Suspenseful'],
    ratingSymbol: 'R',
    ratingDetails: ['language', 'violence', 'terror'],
    description:
      'Incidunt non reiciendis. In explicabo voluptas. Eos delectus ullam unde aliquam. Commodi exercitationem maiores deserunt quia facilis sit ducimus sit sapiente. Aut reiciendis et error officiis voluptatem aspernatur ullam praesentium.',
    id: '78',
  },
  {
    mediaId: 'mediaId 79',
    titleImg: 'titleImg 79',
    mainCategory: '3',
    subCategory: '7',
    mediaType: 'mediaType 79',
    madeAt: '2025-02-11T19:27:24.614Z',
    title: '6 Underground',
    casts: ['Ryan Reynolds', 'Melanie Laurent', 'Corey Hawkins'],
    genres: ['Action', 'Adventure'],
    impressions: ['Adrenaline Rush', 'Exciting'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language', 'blood'],
    description:
      'Vero consequatur adipisci repellat incidunt hic necessitatibus voluptatibus quidem aperiam. Repellat autem explicabo id magnam nisi unde.',
    id: '79',
  },
  {
    mediaId: 'mediaId 80',
    titleImg: 'titleImg 80',
    mainCategory: '1',
    subCategory: '7',
    mediaType: 'mediaType 80',
    madeAt: '2024-08-08T11:19:13.089Z',
    title: 'Polar',
    casts: ['Mads Mikkelsen', 'Vanessa Hudgens', 'Katheryn Winnick'],
    genres: ['Canadian', 'Action', 'Adventure'],
    impressions: ['Violent'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'nudity', 'sex', 'smoking'],
    description:
      'Cumque officiis sed dolorum vero. Vitae magnam quae quaerat eius placeat illum. Illum error veritatis et praesentium architecto. Voluptatem iure in. Quis esse optio dolorum officia. Reiciendis harum fugiat quia quisquam quod inventore labore.',
    id: '80',
  },
  {
    mediaId: 'mediaId 81',
    titleImg: 'titleImg 81',
    mainCategory: '7',
    subCategory: '4',
    mediaType: 'mediaType 81',
    madeAt: '2024-10-03T13:53:10.826Z',
    title: 'Bird Box',
    casts: ['Sandra Bullock', 'Trevante Rhodes', 'John Malkovich'],
    genres: ['Horror Movies', 'Thriller'],
    impressions: ['Chilling', 'Ominous', 'Scary'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'blood', 'language'],
    description:
      'Labore quam ratione. Velit deleniti molestiae placeat dolorum consectetur rem reprehenderit labore. Expedita quisquam autem nam nam id soluta. Quaerat ab unde pariatur cum numquam alias eius. Blanditiis animi nam eaque ullam nisi fugit porro saepe.',
    id: '81',
  },
  {
    mediaId: 'mediaId 82',
    titleImg: 'titleImg 82',
    mainCategory: '1',
    subCategory: '4',
    mediaType: 'mediaType 82',
    madeAt: '2024-06-01T23:48:01.503Z',
    title: 'Dark',
    casts: ['Louis Hofmann', 'Oliver Masucci', 'Jordis Triebel'],
    genres: ['TV Dramas', 'German', 'Sci-Fi TV'],
    impressions: ['Mind-Bending', 'Chilling', 'Ominous'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'nudity', 'sex', 'smoking', 'suicide'],
    description:
      'Voluptatum omnis architecto reiciendis. Optio rerum vel numquam quibusdam error odio. Asperiores doloremque deleniti consequuntur excepturi sunt tenetur aut harum. Inventore fugiat doloribus quae.',
    id: '82',
  },
  {
    mediaId: 'mediaId 83',
    titleImg: 'titleImg 83',
    mainCategory: '3',
    subCategory: '5',
    mediaType: 'mediaType 83',
    madeAt: '2024-12-24T02:28:10.743Z',
    title: 'Now You See Me',
    casts: ['Jesse Eisenberg', 'Mark Ruffalo', 'Woody Harrelson'],
    genres: ['Thriller', 'Mystery'],
    impressions: ['Suspenseful', 'Exciting'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['language', 'action'],
    description:
      'Reprehenderit laudantium tempore expedita. Corporis non alias debitis quibusdam temporibus mollitia. Asperiores voluptates culpa eligendi aliquam excepturi pariatur sapiente. Numquam deserunt sapiente tempore dignissimos maxime cupiditate iure. Deserunt expedita reprehenderit rerum neque deserunt.',
    id: '83',
  },
  {
    mediaId: 'mediaId 84',
    titleImg: 'titleImg 84',
    mainCategory: '8',
    subCategory: '4',
    mediaType: 'mediaType 84',
    madeAt: '2024-06-17T09:59:58.050Z',
    title: 'American Sniper',
    casts: ['Bradley Cooper', 'Sienna Miller', 'Luke Grimes'],
    genres: ['Military Movies', 'Drama Movies'],
    impressions: ['Gritty'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language'],
    description:
      'Placeat praesentium officiis debitis distinctio. Id reiciendis ad voluptates ratione alias illum cum alias facilis. In aperiam velit veritatis quidem modi a laborum architecto eveniet. Corporis nemo explicabo nam enim qui.',
    id: '84',
  },
  {
    mediaId: 'mediaId 85',
    titleImg: 'titleImg 85',
    mainCategory: '4',
    subCategory: '5',
    mediaType: 'mediaType 85',
    madeAt: '2024-12-10T01:15:31.413Z',
    title: 'Den of Thieves',
    casts: ['Gerard Butler', 'Pablo Schreiber', "O'Shea Jackson"],
    genres: ['Action', 'Adventure'],
    impressions: ['Violent', 'Suspenseful', 'Exciting'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language', 'nudity'],
    description:
      'Dignissimos perspiciatis excepturi corporis. Neque praesentium aspernatur a assumenda aliquid eius ullam tenetur. Rerum magnam consequatur quibusdam labore aperiam velit. Repellendus quo labore quos iusto. Beatae velit eveniet ratione dolorum. Explicabo corporis pariatur.',
    id: '85',
  },
  {
    mediaId: 'mediaId 86',
    titleImg: 'titleImg 86',
    mainCategory: '8',
    subCategory: '8',
    mediaType: 'mediaType 86',
    madeAt: '2024-04-18T06:29:06.809Z',
    title: 'The Equalizer 2',
    casts: ['Denzel Washington', 'Pedro Pascal', 'Ashton Sanders'],
    genres: ['Action', 'Adventure'],
    impressions: ['Violent', 'Dark'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language'],
    description:
      'Dicta explicabo sit sapiente fugit quae laborum amet iusto. Esse doloribus praesentium harum perspiciatis minima debitis maxime beatae. Voluptas distinctio consequuntur minus tempore. Veniam iure labore impedit assumenda. Occaecati rerum tempora consectetur officiis nemo natus necessitatibus minus.',
    id: '86',
  },
  {
    mediaId: 'mediaId 87',
    titleImg: 'titleImg 87',
    mainCategory: '9',
    subCategory: '8',
    mediaType: 'mediaType 87',
    madeAt: '2024-06-23T11:57:17.596Z',
    title: 'The Killer',
    casts: ['Michael Fassbender', 'Tilda Swinton', 'Arliss Howard'],
    genres: ['Drama Movies', 'Thriller'],
    impressions: ['Psychological', 'Dark', 'Suspenseful'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language'],
    description:
      'Aspernatur tenetur consequuntur alias non ullam. Magnam quam accusantium. Facilis odio fuga officia accusamus quaerat. Nisi repudiandae doloremque tempore consequuntur odit. Repudiandae praesentium voluptas. Inventore rem molestiae.',
    id: '87',
  },
  {
    mediaId: 'mediaId 88',
    titleImg: 'titleImg 88',
    mainCategory: '9',
    subCategory: '2',
    mediaType: 'mediaType 88',
    madeAt: '2024-08-27T20:12:19.440Z',
    title: 'The Intern',
    casts: ['Robert De Niro', 'Anne Hathaway', 'Rene Russo'],
    genres: ['Comedy Movies'],
    impressions: ['Witty', 'Bittersweet', 'Heartfelt'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['language'],
    description:
      'Harum voluptatum ab voluptatibus non unde delectus. Quae tenetur ducimus accusantium cum exercitationem nostrum reprehenderit minima ea.',
    id: '88',
  },
  {
    mediaId: 'mediaId 89',
    titleImg: 'titleImg 89',
    mainCategory: '4',
    subCategory: '9',
    mediaType: 'mediaType 89',
    madeAt: '2024-07-10T08:42:31.771Z',
    title: 'Chappie',
    casts: ['Sharlto Copley', 'Hugh Jackman', 'Sigourney Weaver'],
    genres: ['Sci-Fi Movies', 'Action', 'Adventure'],
    impressions: ['Explosive', 'Imaginative'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'language', 'nudity'],
    description:
      'Unde nihil consequuntur consequuntur ad officiis libero voluptatibus perspiciatis repellat. Impedit amet perspiciatis minima qui eum repellat. Nisi dolore minus quam animi rerum animi consequuntur itaque consectetur.',
    id: '89',
  },
  {
    mediaId: 'mediaId 90',
    titleImg: 'titleImg 90',
    mainCategory: '3',
    subCategory: '9',
    mediaType: 'mediaType 90',
    madeAt: '2024-06-24T08:58:00.978Z',
    title: 'Dexter',
    casts: ['Michael C.Hall', 'Jennifer Carpenter', 'DAvid Zayas'],
    genres: ['TV Dramas', 'TV Shows', 'Mystery'],
    impressions: ['Ominous', 'Dark'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'nudity', 'violence'],
    description:
      'Similique accusamus sapiente nesciunt iusto quaerat odio. Enim libero modi similique reiciendis. Error voluptatum accusantium. Nam itaque dignissimos ipsa expedita vero. In quas magni accusamus natus possimus dicta velit. Quos natus error ipsa ipsum voluptas deserunt enim ut reiciendis.',
    id: '90',
  },
  {
    mediaId: 'mediaId 91',
    titleImg: 'titleImg 91',
    mainCategory: '4',
    subCategory: '1',
    mediaType: 'mediaType 91',
    madeAt: '2024-06-12T12:10:00.668Z',
    title: 'Inception',
    casts: ['Leonardo DiCaprio', 'Cillian Murphy', 'Tom Hardy'],
    genres: ['Sci-Fi Movie', 'Action', 'Fantasy'],
    impressions: ['Exciting'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['violence', 'action'],
    description:
      'Perferendis maxime molestias atque quam. At vitae cumque voluptatum qui non vel. Voluptatum quae aliquid vitae laudantium perferendis accusantium quia impedit. Deleniti rerum placeat illo culpa.',
    id: '91',
  },
  {
    mediaId: 'mediaId 92',
    titleImg: 'titleImg 92',
    mainCategory: '3',
    subCategory: '6',
    mediaType: 'mediaType 92',
    madeAt: '2024-09-30T03:19:13.915Z',
    title: 'Glitch',
    casts: ['Patrick Brammall', "Genevieve O'Reilly", 'Emma Booth'],
    genres: ['TV Drdamas', 'Australian', 'Mystery'],
    impressions: ['Chilling', 'Scary', 'Imaginative'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'nudity', 'smoking', 'violence'],
    description:
      'Aspernatur voluptatibus cupiditate ipsum. Voluptatibus alias ut reiciendis cum rem velit.',
    id: '92',
  },
  {
    mediaId: 'mediaId 93',
    titleImg: 'titleImg 93',
    mainCategory: '5',
    subCategory: '7',
    mediaType: 'mediaType 93',
    madeAt: '2024-03-28T14:38:19.759Z',
    title: 'The Punisher',
    casts: ['Jon Bernthal', 'Amber Rose', 'Ben Barnes'],
    genres: ['Action', 'Crime'],
    impressions: ['Dark'],
    ratingSymbol: 'R',
    ratingDetails: ['violence', 'gore', 'sex', 'nudity'],
    description:
      'Possimus inventore aliquid fugit natus. Possimus autem velit optio optio velit earum consequatur aliquid cumque. Aliquid consequatur numquam ut quaerat id tempore. Non sint repellendus vitae nemo cupiditate. Ea tempore eius cumque.',
    id: '93',
  },
  {
    mediaId: 'mediaId 94',
    titleImg: 'titleImg 94',
    mainCategory: '4',
    subCategory: '6',
    mediaType: 'mediaType 94',
    madeAt: '2024-08-21T23:00:20.569Z',
    title: 'Scream',
    casts: ['Neve Campbell', 'David Arquette', 'Courteney Cox'],
    genres: ['Horror Movies', 'Teen Movies'],
    impressions: ['Scary'],
    ratingSymbol: 'R',
    ratingDetails: ['horror', 'violence', 'gore', 'language'],
    description:
      'Accusantium commodi eaque repudiandae. Accusamus impedit cumque odit molestias deserunt quas occaecati.',
    id: '94',
  },
  {
    mediaId: 'mediaId 95',
    titleImg: 'titleImg 95',
    mainCategory: '4',
    subCategory: '5',
    mediaType: 'mediaType 95',
    madeAt: '2024-04-09T00:52:14.962Z',
    title: 'The Hunger Games',
    casts: ['Jennifer Lawrence', 'Josh Hutcherson', 'Liam Hemsworth'],
    genres: ['Sci-Fi Movies', 'Drama Movies'],
    impressions: ['Rousing', 'Bittersweet'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['violence', 'action'],
    description:
      'Labore eum ratione labore ad. Ut minus suscipit nihil officiis aliquid natus rem ipsam totam. Cumque vero vel dolorem numquam. Nam ex nobis culpa maxime praesentium atque.',
    id: '95',
  },
  {
    mediaId: 'mediaId 96',
    titleImg: 'titleImg 96',
    mainCategory: '9',
    subCategory: '7',
    mediaType: 'mediaType 96',
    madeAt: '2025-01-10T01:57:33.616Z',
    title: 'Limitless',
    casts: ['Bradley Cooper', 'Robert De Niro', 'Abbie Cornish'],
    genres: ['Sci-Fi Movie', 'Thriller'],
    impressions: ['Exciting'],
    ratingSymbol: 'PG-13',
    ratingDetails: ['violence', 'drug', 'language'],
    description:
      'Aliquid incidunt facere commodi. Atque perferendis voluptas fugit dolor a soluta. Quis facilis ratione. Ducimus alias similique nihil rerum sapiente deserunt ratione. Possimus aspernatur perspiciatis enim. Neque expedita culpa repudiandae sequi fuga pariatur dolorum.',
    id: '96',
  },
  {
    mediaId: 'mediaId 97',
    titleImg: 'titleImg 97',
    mainCategory: '4',
    subCategory: '1',
    mediaType: 'mediaType 97',
    madeAt: '2024-09-06T21:12:07.547Z',
    title: 'OtherLife',
    casts: ['Jessica De Gouw', 'Liam Graham', 'T.J.Power'],
    genres: ['Sci-Fi Movie', 'Crime', 'Thriller'],
    impressions: ['Exciting', 'Rousing', 'Dark'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['violence', 'action'],
    description:
      'Adipisci cumque maxime velit consequuntur aliquam voluptates illum voluptates ad. Nihil perferendis rem omnis laboriosam quam accusantium in tempora mollitia. Eligendi soluta incidunt perspiciatis.',
    id: '97',
  },
  {
    mediaId: 'mediaId 98',
    titleImg: 'titleImg 98',
    mainCategory: '4',
    subCategory: '9',
    mediaType: 'mediaType 98',
    madeAt: '2024-11-03T00:37:17.838Z',
    title: 'House of Cards',
    casts: ['Robin Wright', 'Michael Kelly', 'Diane Lane'],
    genres: ['TV Dramas', 'TV Thrillers'],
    impressions: ['Cerebral', 'Dark'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'nudity', 'sex', 'smoking', 'violence'],
    description:
      'Veritatis iusto ipsam tempore voluptates nam fugit enim nostrum. Eaque esse ratione tempore facere rerum quaerat molestias commodi. Aliquam culpa impedit minus.',
    id: '98',
  },
  {
    mediaId: 'mediaId 99',
    titleImg: 'titleImg 99',
    mainCategory: '2',
    subCategory: '9',
    mediaType: 'mediaType 99',
    madeAt: '2024-10-26T01:29:00.758Z',
    title: 'Altered Carbon',
    casts: ['Anthony Mackie', 'Lela Loren', 'Simone Missick'],
    genres: ['TV Dramas', 'Sci-Fi TV'],
    impressions: ['Mind-Bending', 'Violent'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['language', 'nudity', 'sex', 'violence', 'smoking'],
    description:
      'Doloremque distinctio accusantium deserunt perferendis iste. Dolores repellat dolorum quis sequi laboriosam. Aut iusto eum quibusdam nihil nobis earum. Quisquam quis inventore vero. Odit possimus voluptatibus eveniet. Repudiandae laboriosam quibusdam laboriosam earum.',
    id: '99',
  },
  {
    mediaId: 'mediaId 100',
    titleImg: 'titleImg 100',
    mainCategory: '5',
    subCategory: '3',
    mediaType: 'mediaType 100',
    madeAt: '2025-02-06T07:44:56.341Z',
    title: 'Mindhunter',
    casts: ['Jonathan Groff', 'Holt McCallany', 'Anna Torv'],
    genres: ['TV Dramas', 'Mystery'],
    impressions: ['Chilling', 'Psychological'],
    ratingSymbol: 'TV-MA',
    ratingDetails: ['gore', 'language', 'nudity', 'violence'],
    description:
      'Ex illo facilis expedita dolorum pariatur voluptate minima omnis ex. Pariatur veritatis optio sequi necessitatibus laborum illo odit voluptatem.',
    id: '100',
  },
]
